
import { Word } from './types.ts';

export const WORLDS = [
  { id: 1, name: "Ancient Valley (Unit 1)", theme: "emerald" },
  { id: 2, name: "Cozy Sanctuary (Unit 2)", theme: "amber" },
  { id: 3, name: "Social Plaza (Unit 3)", theme: "blue" },
  { id: 4, name: "Adventure Peak (Unit 4)", theme: "purple" },
  { id: 5, name: "Health Canyon (Unit 5)", theme: "indigo" },
  { id: 6, name: "Future City (Unit 6)", theme: "cyan" },
  { id: 7, name: "Gourmet Island (Unit 7)", theme: "rose" },
  { id: 8, name: "Wisdom Temple (Unit 8)", theme: "orange" }
];
// ... 单词数据保持不变 ...
const u1: Word[] = [
  { id: 'u1-1', english: 'ancient', chinese: '古代的', pos: 'adj', example: 'This is an ancient building.', exampleChinese: '这是一座古老的建筑。' },
  { id: 'u1-2', english: 'camp', chinese: '营地', pos: 'n', example: 'We stay at the camp.', exampleChinese: '我们呆在营地里。' },
  { id: 'u1-3', english: 'landscape', chinese: '风景', pos: 'n', example: 'The landscape is beautiful.', exampleChinese: '这里的景色非常美丽。' },
  { id: 'u1-4', english: 'strange', chinese: '奇怪的', pos: 'adj', example: 'That is a strange bird.', exampleChinese: '那是一只奇怪的鸟。' },
  { id: 'u1-5', english: 'vacation', chinese: '假期', pos: 'n', example: 'I like my summer vacation.', exampleChinese: '我喜欢我的暑假。' },
  { id: 'u1-6', english: 'fantastic', chinese: '极好的', pos: 'adj', example: 'We had a fantastic time.', exampleChinese: '我们度过了一段极好的时光。' },
  { id: 'u1-7', english: 'town', chinese: '城镇', pos: 'n', example: 'My town is very small.', exampleChinese: '我的城镇非常小。' },
  { id: 'u1-8', english: 'comfortable', chinese: '舒适的', pos: 'adj', example: 'This sofa is comfortable.', exampleChinese: '这张沙发很舒适。' },
  { id: 'u1-9', english: 'scenery', chinese: '景色', pos: 'n', example: 'I love mountain scenery.', exampleChinese: '我喜欢山里的景色。' },
  { id: 'u1-10', english: 'valley', chinese: '山谷', pos: 'n', example: 'The river is in the valley.', exampleChinese: '这条河在山谷里。' },
  { id: 'u1-11', english: 'probably', chinese: '大概', pos: 'adv', example: 'It will probably rain.', exampleChinese: '今天大概会下雨。' },
  { id: 'u1-12', english: 'bridge', chinese: '桥', pos: 'n', example: 'The bridge is long.', exampleChinese: '这座桥非常长。' },
  { id: 'u1-13', english: 'luckily', chinese: '幸运地', pos: 'adv', example: 'Luckily the rain stopped.', exampleChinese: '幸运的是，雨停了。' },
  { id: 'u1-14', english: 'nature', chinese: '自然', pos: 'n', example: 'I love nature.', exampleChinese: '我热爱大自然。' },
  { id: 'u1-15', english: 'mountain', chinese: '山', pos: 'n', example: 'The mountain is high.', exampleChinese: '这座山很高。' },
  { id: 'u1-16', english: 'forest', chinese: '森林', pos: 'n', example: 'Trees grow in the forest.', exampleChinese: '森林里长了很多树。' },
  { id: 'u1-17', english: 'quiet', chinese: '安静的', pos: 'adj', example: 'The room is quiet.', exampleChinese: '房间里非常安静。' },
  { id: 'u1-18', english: 'village', chinese: '村庄', pos: 'n', example: 'He lives in a village.', exampleChinese: '他住在一个村庄里。' },
  { id: 'u1-19', english: 'journey', chinese: '旅程', pos: 'n', example: 'Have a nice journey.', exampleChinese: '祝你旅途愉快。' },
  { id: 'u1-20', english: 'history', chinese: '历史', pos: 'n', example: 'China has long history.', exampleChinese: '中国有悠久的历史。' },
  { id: 'u1-21', english: 'delicious', chinese: '美味的', pos: 'adj', example: 'The food is delicious.', exampleChinese: '食物很美味。' },
  { id: 'u1-22', english: 'experience', chinese: '经验', pos: 'n', example: 'It was a great experience.', exampleChinese: '那是一段伟大的经历。' },
  { id: 'u1-23', english: 'activity', chinese: '活动', pos: 'n', example: 'This is a fun activity.', exampleChinese: '这是一个有趣的活动。' },
  { id: 'u1-24', english: 'different', chinese: '不同的', pos: 'adj', example: 'They are different.', exampleChinese: '它们是不同的。' },
  { id: 'u1-25', english: 'popular', chinese: '流行的', pos: 'adj', example: 'Football is popular.', exampleChinese: '足球很流行。' },
  { id: 'u1-26', english: 'culture', chinese: '文化', pos: 'n', example: 'We love our culture.', exampleChinese: '我们热爱我们的文化。' },
  { id: 'u1-27', english: 'standard', chinese: '标准', pos: 'n', example: 'He has high standards.', exampleChinese: '他有很高的标准。' },
  { id: 'u1-28', english: 'certainly', chinese: '当然', pos: 'adv', example: 'I will certainly help.', exampleChinese: '我当然会帮助。' },
  { id: 'u1-29', english: 'especially', chinese: '尤其', pos: 'adv', example: 'I like fruit especially apples.', exampleChinese: '我喜欢水果，尤其是苹果。' },
  { id: 'u1-30', english: 'actually', chinese: '实际上', pos: 'adv', example: 'Actually I know him.', exampleChinese: '实际上，我认识他。' },
  { id: 'u1-31', english: 'simply', chinese: '简单地', pos: 'adv', example: 'Just do it simply.', exampleChinese: '就简单地做吧。' },
  { id: 'u1-32', english: 'suddenly', chinese: '突然', pos: 'adv', example: 'Suddenly it rained.', exampleChinese: '突然，天开始下雨了。' }
];
// ... 后续 Unit 保持不变 ...
const u2: Word[] = [
  { id: 'u2-1', english: 'pack', chinese: '打包', pos: 'v', example: 'Pack your bags.', exampleChinese: '打包你的行李。' },
  { id: 'u2-2', english: 'bathroom', chinese: '浴室', pos: 'n', example: 'The bathroom is clean.', exampleChinese: '浴室很干净。' },
  { id: 'u2-3', english: 'kitchen', chinese: '厨房', pos: 'n', example: 'Mom is in the kitchen.', exampleChinese: '妈妈在厨房里。' },
  { id: 'u2-4', english: 'bedroom', chinese: '卧室', pos: 'n', example: 'Go to your bedroom.', exampleChinese: '回你的卧室。' },
  { id: 'u2-5', english: 'living', chinese: '生活的', pos: 'adj', example: 'The living room is big.', exampleChinese: '客厅很大。' },
  { id: 'u2-6', english: 'furniture', chinese: '家具', pos: 'n', example: 'We bought new furniture.', exampleChinese: '我们买了新家具。' },
  { id: 'u2-7', english: 'fridge', chinese: '冰箱', pos: 'n', example: 'Milk is in the fridge.', exampleChinese: '牛奶在冰箱里。' },
  { id: 'u2-8', english: 'microwave', chinese: '微波炉', pos: 'n', example: 'Use the microwave.', exampleChinese: '用微波炉吧。' },
  { id: 'u2-9', english: 'curtain', chinese: '窗帘', pos: 'n', example: 'Close the curtain.', exampleChinese: '关上窗帘。' },
  { id: 'u2-10', english: 'cushion', chinese: '垫子', pos: 'n', example: 'Sit on the cushion.', exampleChinese: '坐在垫子上。' },
  { id: 'u2-11', english: 'neighbor', chinese: '邻居', pos: 'n', example: 'He is my neighbor.', exampleChinese: '他是我的邻居。' },
  { id: 'u2-12', english: 'apartment', chinese: '公寓', pos: 'n', example: 'I live in an apartment.', exampleChinese: '我住在公寓里。' },
  { id: 'u2-13', english: 'tidy', chinese: '整洁的', pos: 'adj', example: 'Keep your room tidy.', exampleChinese: '保持房间整洁。' },
  { id: 'u2-14', english: 'messy', chinese: '凌乱的', pos: 'adj', example: 'Your room is messy.', exampleChinese: '你的房间很乱。' },
  { id: 'u2-15', english: 'clean', chinese: '打扫', pos: 'v', example: 'Clean the floor.', exampleChinese: '清扫地板。' },
  { id: 'u2-16', english: 'sweep', chinese: '扫', pos: 'v', example: 'Sweep the floor.', exampleChinese: '扫地。' },
  { id: 'u2-17', english: 'repair', chinese: '修理', pos: 'v', example: 'Repair the chair.', exampleChinese: '修理椅子。' },
  { id: 'u2-18', english: 'fix', chinese: '固定', pos: 'v', example: 'Fix the light.', exampleChinese: '修好那个灯。' },
  { id: 'u2-19', english: 'shelf', chinese: '书架', pos: 'n', example: 'Put it on the shelf.', exampleChinese: '把它放到架子上。' },
  { id: 'u2-20', english: 'mirror', chinese: '镜子', pos: 'n', example: 'Look in the mirror.', exampleChinese: '照照镜子。' },
  { id: 'u2-21', english: 'carpet', chinese: '地毯', pos: 'n', example: 'A red carpet.', exampleChinese: '一张红地毯。' },
  { id: 'u2-22', english: 'invite', chinese: '邀请', pos: 'v', example: 'Invite your friends.', exampleChinese: '邀请你的朋友。' },
  { id: 'u2-23', english: 'guest', chinese: '客人', pos: 'n', example: 'We have a guest.', exampleChinese: '我们有客人。' },
  { id: 'u2-24', english: 'prepare', chinese: '准备', pos: 'v', example: 'Prepare the dinner.', exampleChinese: '准备晚饭。' },
  { id: 'u2-25', english: 'housework', chinese: '家务', pos: 'n', example: 'I do housework.', exampleChinese: '我做家务。' },
  { id: 'u2-26', english: 'laundry', chinese: '洗衣', pos: 'n', example: 'Do the laundry.', exampleChinese: '洗衣服。' },
  { id: 'u2-27', english: 'decorate', chinese: '装饰', pos: 'v', example: 'Decorate the tree.', exampleChinese: '装饰那棵树。' },
  { id: 'u2-28', english: 'balcony', chinese: '阳台', pos: 'n', example: 'Stand on the balcony.', exampleChinese: '站在阳台上。' },
  { id: 'u2-29', english: 'storage', chinese: '储藏', pos: 'n', example: 'We need storage.', exampleChinese: '我们需要储藏空间。' },
  { id: 'u2-30', english: 'basement', chinese: '地下室', pos: 'n', example: 'Go to the basement.', exampleChinese: '去地下室。' },
  { id: 'u2-31', english: 'garden', chinese: '花园', pos: 'n', example: 'Flowers in the garden.', exampleChinese: '花园里的花。' },
  { id: 'u2-32', english: 'backyard', chinese: '后院', pos: 'n', example: 'Play in the backyard.', exampleChinese: '在后院玩。' }
];
// ... 后续 Unit 保持不变 ...
const u3: Word[] = [
  { id: 'u3-1', english: 'student', chinese: '学生', pos: 'n', example: 'He is a good student.', exampleChinese: '他是个好学生。' },
  { id: 'u3-2', english: 'teacher', chinese: '老师', pos: 'n', example: 'My teacher is very kind.', exampleChinese: '我的老师非常和蔼。' },
  { id: 'u3-3', english: 'library', chinese: '图书馆', pos: 'n', example: 'I study in the library.', exampleChinese: '我在图书馆学习。' },
  { id: 'u3-4', english: 'subject', chinese: '科目', pos: 'n', example: 'Math is my favorite subject.', exampleChinese: '数学是我最喜欢的科目。' },
  { id: 'u3-5', english: 'science', chinese: '科学', pos: 'n', example: 'We learn science at school.', exampleChinese: '我们在学校学习科学。' },
  { id: 'u3-6', english: 'project', chinese: '项目', pos: 'n', example: 'We finished the school project.', exampleChinese: '我们完成了学校项目。' },
  { id: 'u3-7', english: 'grade', chinese: '成绩', pos: 'n', example: 'She got a high grade.', exampleChinese: '她得到了高分。' },
  { id: 'u3-8', english: 'primary', chinese: '初级的', pos: 'adj', example: 'He goes to primary school.', exampleChinese: '他在上小学。' },
  { id: 'u3-9', english: 'friend', chinese: '朋友', pos: 'n', example: 'They are my best friends.', exampleChinese: '他们是我最好的朋友。' },
  { id: 'u3-10', english: 'group', chinese: '小组', pos: 'n', example: 'Please work in a group.', exampleChinese: '请分组合作。' },
  { id: 'u3-11', english: 'conversation', chinese: '对话', pos: 'n', example: 'We had a short conversation.', exampleChinese: '我们进行了一段简短的对话。' },
  { id: 'u3-12', english: 'listen', chinese: '听', pos: 'v', example: 'Please listen to the teacher.', exampleChinese: '请听老师讲。' },
  { id: 'u3-13', english: 'speak', chinese: '说', pos: 'v', example: 'Can you speak English well?', exampleChinese: '你能说好英语吗？' },
  { id: 'u3-14', english: 'share', chinese: '分享', pos: 'v', example: 'I share my toys with you.', exampleChinese: '我和你分享玩具。' },
  { id: 'u3-15', english: 'helpful', chinese: '有帮助的', pos: 'adj', example: 'Your advice is very helpful.', exampleChinese: '你的建议非常有帮助。' },
  { id: 'u3-16', english: 'together', chinese: '一起', pos: 'adv', example: 'Let us go home together.', exampleChinese: '让我们一起回家吧。' },
  { id: 'u3-17', english: 'classroom', chinese: '教室', pos: 'n', example: 'Our classroom is very bright.', exampleChinese: '我们的教室非常明亮。' },
  { id: 'u3-18', english: 'blackboard', chinese: '黑板', pos: 'n', example: 'The teacher writes on the blackboard.', exampleChinese: '老师在黑板上写字。' },
  { id: 'u3-19', english: 'desk', chinese: '书桌', pos: 'n', example: 'Put your books on the desk.', exampleChinese: '把你的书放在书桌上。' },
  { id: 'u3-20', english: 'exercise', chinese: '练习', pos: 'n', example: 'Do your English exercise now.', exampleChinese: '现在做你的英语练习。' },
  { id: 'u3-21', english: 'physical', chinese: '身体的', pos: 'adj', example: 'I like physical education class.', exampleChinese: '我喜欢体育课。' },
  { id: 'u3-22', english: 'uniform', chinese: '制服', pos: 'n', example: 'I wear a school uniform.', exampleChinese: '我穿着校服。' },
  { id: 'u3-23', english: 'rule', chinese: '规则', pos: 'n', example: 'We must follow the rules.', exampleChinese: '我们必须遵守规则。' },
  { id: 'u3-24', english: 'careful', chinese: '小心的', pos: 'adj', example: 'You should be more careful.', exampleChinese: '你应该更小心一点。' },
  { id: 'u3-25', english: 'active', chinese: '活跃的', pos: 'adj', example: 'The student is very active.', exampleChinese: '那个学生很活跃。' },
  { id: 'u3-26', english: 'participate', chinese: '参加', pos: 'v', example: 'They participate in the game.', exampleChinese: '他们参加了游戏。' },
  { id: 'u3-27', english: 'question', chinese: '问题', pos: 'n', example: 'I have an easy question.', exampleChinese: '我有一个简单的问题。' },
  { id: 'u3-28', english: 'answer', chinese: '回答', pos: 'v', example: 'Please answer my question.', exampleChinese: '请回答我的问题。' },
  { id: 'u3-29', english: 'correct', chinese: '正确的', pos: 'adj', example: 'That is the correct way.', exampleChinese: '那是正确的方法。' },
  { id: 'u3-30', english: 'mistake', chinese: '错误', pos: 'n', example: 'Everyone makes a small mistake.', exampleChinese: '每个人都会犯小错。' },
  { id: 'u3-31', english: 'learn', chinese: '学习', pos: 'v', example: 'I want to learn swimming.', exampleChinese: '我想学习游泳。' },
  { id: 'u3-32', english: 'progress', chinese: '进步', pos: 'n', example: 'You make progress in English.', exampleChinese: '你在英语上取得了进步。' }
];

const u4: Word[] = [
  { id: 'u4-1', english: 'explore', chinese: '探索', pos: 'v', example: 'We will explore the forest.', exampleChinese: '我们将探索这片森林。' },
  { id: 'u4-2', english: 'journey', chinese: '旅程', pos: 'n', example: 'Our journey was very long.', exampleChinese: '我们的旅程很漫长。' },
  { id: 'u4-3', english: 'direction', chinese: '方向', pos: 'n', example: 'Walk in the right direction.', exampleChinese: '走向正确的方向。' },
  { id: 'u4-4', english: 'guide', chinese: '向导', pos: 'n', example: 'The guide showed us around.', exampleChinese: '向导带我们四处参观。' },
  { id: 'u4-5', english: 'map', chinese: '地图', pos: 'n', example: 'I cannot read the map.', exampleChinese: '我看不懂这张地图。' },
  { id: 'u4-6', english: 'forest', chinese: '森林', pos: 'n', example: 'The forest is dark today.', exampleChinese: '今天的森林很阴暗。' },
  { id: 'u4-7', english: 'path', chinese: '小路', pos: 'n', example: 'Follow the narrow path here.', exampleChinese: '沿着这里的窄路走。' },
  { id: 'u4-8', english: 'wild', chinese: '野生的', pos: 'adj', example: 'Wild flowers are very beautiful.', exampleChinese: '野花非常漂亮。' },
  { id: 'u4-9', english: 'prepare', chinese: '准备', pos: 'v', example: 'I will prepare some food.', exampleChinese: '我会准备一些食物。' },
  { id: 'u4-10', english: 'equipment', chinese: '装备', pos: 'n', example: 'Check your camping equipment now.', exampleChinese: '现在检查你的野营装备。' },
  { id: 'u4-11', english: 'backpack', chinese: '背包', pos: 'n', example: 'Put water into your backpack.', exampleChinese: '把水放进你的背包里。' },
  { id: 'u4-12', english: 'camping', chinese: '野营', pos: 'n', example: 'We love camping in summer.', exampleChinese: '我们喜欢在夏天野营。' },
  { id: 'u4-13', english: 'fire', chinese: '火', pos: 'n', example: 'Do not play with fire.', exampleChinese: '不要玩火。' },
  { id: 'u4-14', english: 'wood', chinese: '木头', pos: 'n', example: 'This desk is made of wood.', exampleChinese: '这张桌子是木头做的。' },
  { id: 'u4-15', english: 'light', chinese: '灯', pos: 'n', example: 'Please turn on the light.', exampleChinese: '请开灯。' },
  { id: 'u4-16', english: 'dark', chinese: '黑暗的', pos: 'adj', example: 'The cave is very dark.', exampleChinese: '洞穴里非常黑暗。' },
  { id: 'u4-17', english: 'exciting', chinese: '令人兴奋的', pos: 'adj', example: 'The film is very exciting.', exampleChinese: '这部电影非常刺激。' },
  { id: 'u4-18', english: 'danger', chinese: '危险', pos: 'n', example: 'We are in great danger.', exampleChinese: '我们处于极大的危险中。' },
  { id: 'u4-19', english: 'safe', chinese: '安全的', pos: 'adj', example: 'It is safe to cross.', exampleChinese: '过马路是安全的。' },
  { id: 'u4-20', english: 'mountain', chinese: '山脉', pos: 'n', example: 'The mountain is very high.', exampleChinese: '这座山非常高。' },
  { id: 'u4-21', english: 'cave', chinese: '洞穴', pos: 'n', example: 'A big bear lives here.', exampleChinese: '一只大熊住在这个洞穴。' },
  { id: 'u4-22', english: 'hidden', chinese: '隐藏的', pos: 'adj', example: 'I found a hidden treasure.', exampleChinese: '我发现了一处隐藏的宝藏。' },
  { id: 'u4-23', english: 'treasure', chinese: '宝藏', pos: 'n', example: 'The treasure is in a box.', exampleChinese: '宝藏在一个盒子里。' },
  { id: 'u4-24', english: 'search', chinese: '寻找', pos: 'v', example: 'I search for my key.', exampleChinese: '我寻找我的钥匙。' },
  { id: 'u4-25', english: 'reach', chinese: '到达', pos: 'v', example: 'We will reach the top.', exampleChinese: '我们将到达山顶。' },
  { id: 'u4-26', english: 'top', chinese: '顶部', pos: 'n', example: 'He is at the top.', exampleChinese: '他在顶部。' },
  { id: 'u4-27', english: 'view', chinese: '视野', pos: 'n', example: 'The view is great here.', exampleChinese: '这里的视野很棒。' },
  { id: 'u4-28', english: 'wonder', chinese: '奇迹', pos: 'n', example: 'Nature is a great wonder.', exampleChinese: '大自然是一个伟大的奇迹。' },
  { id: 'u4-29', english: 'incredible', chinese: '不可思议的', pos: 'adj', example: 'The news is really incredible.', exampleChinese: '这个消息真令人难以置信。' },
  { id: 'u4-30', english: 'island', chinese: '岛屿', pos: 'n', example: 'We live on a small island.', exampleChinese: '我们住在一个小岛上。' },
  { id: 'u4-31', english: 'lake', chinese: '湖泊', pos: 'n', example: 'The lake is very clear.', exampleChinese: '湖水非常清澈。' },
  { id: 'u4-32', english: 'river', chinese: '河流', pos: 'n', example: 'The river flows into sea.', exampleChinese: '这条河流入大海。' }
];

const u5: Word[] = [
  { id: 'u5-1', english: 'health', chinese: '健康', pos: 'n', example: 'Health is very important.', exampleChinese: '健康非常重要。' },
  { id: 'u5-2', english: 'fit', chinese: '健康的', pos: 'adj', example: 'He runs to keep fit.', exampleChinese: '他跑步以保持健康。' },
  { id: 'u5-3', english: 'body', chinese: '身体', pos: 'n', example: 'Exercise is good for body.', exampleChinese: '运动对身体有好处。' },
  { id: 'u5-4', english: 'exercise', chinese: '运动', pos: 'v', example: 'You should exercise every day.', exampleChinese: '你应该每天运动。' },
  { id: 'u5-5', english: 'run', chinese: '跑步', pos: 'v', example: 'I can run very fast.', exampleChinese: '我跑得很快。' },
  { id: 'u5-6', english: 'swim', chinese: '游泳', pos: 'v', example: 'Can you swim in sea?', exampleChinese: '你能在海里游泳吗？' },
  { id: 'u5-7', english: 'strong', chinese: '强壮的', pos: 'adj', example: 'My father is very strong.', exampleChinese: '我的父亲非常强壮。' },
  { id: 'u5-8', english: 'energy', chinese: '能量', pos: 'n', example: 'Fruit gives us much energy.', exampleChinese: '水果给我们很多能量。' },
  { id: 'u5-9', english: 'doctor', chinese: '医生', pos: 'n', example: 'The doctor is very kind.', exampleChinese: '这位医生很和蔼。' },
  { id: 'u5-10', english: 'nurse', chinese: '护士', pos: 'n', example: 'A nurse works in hospital.', exampleChinese: '护士在医院工作。' },
  { id: 'u5-11', english: 'hospital', chinese: '医院', pos: 'n', example: 'He is in the hospital.', exampleChinese: '他在医院里。' },
  { id: 'u5-12', english: 'check', chinese: '检查', pos: 'v', example: 'Please check your work again.', exampleChinese: '请再检查一下你的作业。' },
  { id: 'u5-13', english: 'heart', chinese: '心脏', pos: 'n', example: 'My heart beats fast now.', exampleChinese: '我现在心跳很快。' },
  { id: 'u5-14', english: 'blood', chinese: '血液', pos: 'n', example: 'Blood is red in color.', exampleChinese: '血液是红色的。' },
  { id: 'u5-15', english: 'breathe', chinese: '呼吸', pos: 'v', example: 'Breathe the fresh air now.', exampleChinese: '现在呼吸新鲜空气吧。' },
  { id: 'u5-16', english: 'lung', chinese: '肺', pos: 'n', example: 'We have two lungs.', exampleChinese: '我们有两个肺。' },
  { id: 'u5-17', english: 'fresh', chinese: '新鲜的', pos: 'adj', example: 'The air is very fresh.', exampleChinese: '空气非常新鲜。' },
  { id: 'u5-18', english: 'vegetable', chinese: '蔬菜', pos: 'n', example: 'I like eating green vegetables.', exampleChinese: '我喜欢吃绿叶蔬菜。' },
  { id: 'u5-19', english: 'fruit', chinese: '水果', pos: 'n', example: 'Apple is a kind of fruit.', exampleChinese: '苹果是一种水果。' },
  { id: 'u5-20', english: 'balanced', chinese: '平衡的', pos: 'adj', example: 'We need a balanced diet.', exampleChinese: '我们需要平衡饮食。' },
  { id: 'u5-21', english: 'diet', chinese: '饮食', pos: 'n', example: 'What is your daily diet?', exampleChinese: '你平时的饮食是什么？' },
  { id: 'u5-22', english: 'sugar', chinese: '糖', pos: 'n', example: 'Do not eat too much sugar.', exampleChinese: '不要吃太多的糖。' },
  { id: 'u5-23', english: 'avoid', chinese: '避免', pos: 'v', example: 'You should avoid fast food.', exampleChinese: '你应该避免吃快餐。' },
  { id: 'u5-24', english: 'habit', chinese: '习惯', pos: 'n', example: 'Drinking water is a good habit.', exampleChinese: '喝水是一个好习惯。' },
  { id: 'u5-25', english: 'sleep', chinese: '睡觉', pos: 'v', example: 'I sleep eight hours a day.', exampleChinese: '我一天睡八小时。' },
  { id: 'u5-26', english: 'rest', chinese: '休息', pos: 'v', example: 'Let us have a rest.', exampleChinese: '让我们休息一下吧。' },
  { id: 'u5-27', english: 'relax', chinese: '放松', pos: 'v', example: 'Music makes me feel relax.', exampleChinese: '音乐让我感到放松。' },
  { id: 'u5-28', english: 'stress', chinese: '压力', pos: 'n', example: 'I have some school stress.', exampleChinese: '我有一些学业压力。' },
  { id: 'u5-29', english: 'mental', chinese: '精神的', pos: 'adj', example: 'Mental health is also important.', exampleChinese: '心理健康同样重要。' },
  { id: 'u5-30', english: 'smile', chinese: '微笑', pos: 'v', example: 'She has a beautiful smile.', exampleChinese: '她有美丽的微笑。' },
  { id: 'u5-31', english: 'happy', chinese: '快乐的', pos: 'adj', example: 'I am happy to see you.', exampleChinese: '我很开心见到你。' },
  { id: 'u5-32', english: 'life', chinese: '生活', pos: 'n', example: 'Enjoy your life every day.', exampleChinese: '享受每一天的生活。' }
];

const u6: Word[] = [
  { id: 'u6-1', english: 'technology', chinese: '技术', pos: 'n', example: 'Technology makes our life easy.', exampleChinese: '技术让我们的生活变得简单。' },
  { id: 'u6-2', english: 'internet', chinese: '互联网', pos: 'n', example: 'We use the internet to learn.', exampleChinese: '我们用互联网学习。' },
  { id: 'u6-3', english: 'computer', chinese: '电脑', pos: 'n', example: 'I have a new computer.', exampleChinese: '我有一台新电脑。' },
  { id: 'u6-4', english: 'robot', chinese: '机器人', pos: 'n', example: 'The robot can help us.', exampleChinese: '机器人可以帮助我们。' },
  { id: 'u6-5', english: 'machine', chinese: '机器', pos: 'n', example: 'This is a cleaning machine.', exampleChinese: '这是一台清洁机器。' },
  { id: 'u6-6', english: 'system', chinese: '系统', pos: 'n', example: 'The sun is in solar system.', exampleChinese: '太阳在太阳系中。' },
  { id: 'u6-7', english: 'smart', chinese: '聪明的', pos: 'adj', example: 'He is a smart boy.', exampleChinese: '他是个聪明的男孩。' },
  { id: 'u6-8', english: 'future', chinese: '未来', pos: 'n', example: 'Who knows the future?', exampleChinese: '谁知道未来呢？' },
  { id: 'u6-9', english: 'connection', chinese: '连接', pos: 'n', example: 'The connection is very slow.', exampleChinese: '连接非常慢。' },
  { id: 'u6-10', english: 'signal', chinese: '信号', pos: 'n', example: 'The phone signal is weak.', exampleChinese: '手机信号很弱。' },
  { id: 'u6-11', english: 'wire', chinese: '电线', pos: 'n', example: 'Do not touch the wire.', exampleChinese: '不要碰电线。' },
  { id: 'u6-12', english: 'wireless', chinese: '无线的', pos: 'adj', example: 'I use a wireless mouse.', exampleChinese: '我用无线鼠标。' },
  { id: 'u6-13', english: 'battery', chinese: '电池', pos: 'n', example: 'My battery is low now.', exampleChinese: '我的电量低了。' },
  { id: 'u6-14', english: 'power', chinese: '力量', pos: 'n', example: 'Knowledge is great power.', exampleChinese: '知识就是力量。' },
  { id: 'u6-15', english: 'charge', chinese: '充电', pos: 'v', example: 'I must charge my phone.', exampleChinese: '我必须给手机充电。' },
  { id: 'u6-16', english: 'electricity', chinese: '电力', pos: 'n', example: 'The machine needs electricity.', exampleChinese: '这台机器需要电。' },
  { id: 'u6-17', english: 'space', chinese: '空间', pos: 'n', example: 'There is some space here.', exampleChinese: '这儿有一些空间。' },
  { id: 'u6-18', english: 'rocket', chinese: '火箭', pos: 'n', example: 'The rocket flies very high.', exampleChinese: '火箭飞得很高。' },
  { id: 'u6-19', english: 'astronaut', chinese: '宇航员', pos: 'n', example: 'He wants to be an astronaut.', exampleChinese: '他想当一名宇航员。' },
  { id: 'u6-20', english: 'planet', chinese: '行星', pos: 'n', example: 'Earth is our home planet.', exampleChinese: '地球是我们的母星。' },
  { id: 'u6-21', english: 'mars', chinese: '火星', pos: 'n', example: 'Mars is called red planet.', exampleChinese: '火星被称为红色行星。' },
  { id: 'u6-22', english: 'earth', chinese: '地球', pos: 'n', example: 'We should protect the Earth.', exampleChinese: '我们应该保护地球。' },
  { id: 'u6-23', english: 'orbit', chinese: '轨道', pos: 'n', example: 'Moon is in Earth orbit.', exampleChinese: '月球在地球轨道上。' },
  { id: 'u6-24', english: 'galaxy', chinese: '星系', pos: 'n', example: 'The galaxy is very large.', exampleChinese: '星系非常巨大。' },
  { id: 'u6-25', english: 'invent', chinese: '发明', pos: 'v', example: 'Edison invented the light bulb.', exampleChinese: '爱迪生发明了灯泡。' },
  { id: 'u6-26', english: 'create', chinese: '创造', pos: 'v', example: 'We create a new world.', exampleChinese: '我们创造一个新世界。' },
  { id: 'u6-27', english: 'design', chinese: '设计', pos: 'v', example: 'She can design beautiful clothes.', exampleChinese: '她会设计漂亮的衣服。' },
  { id: 'u6-28', english: 'simple', chinese: '简单的', pos: 'adj', example: 'The question is very simple.', exampleChinese: '这个问题很简单。' },
  { id: 'u6-29', english: 'complex', chinese: '复杂的', pos: 'adj', example: 'This is a complex system.', exampleChinese: '这是一个复杂的系统。' },
  { id: 'u6-30', english: 'speed', chinese: '速度', pos: 'n', example: 'The car has high speed.', exampleChinese: '这辆车速度很快。' },
  { id: 'u6-31', english: 'fast', chinese: '快的', pos: 'adj', example: 'He is a fast runner.', exampleChinese: '他是个很快的跑者。' },
  { id: 'u6-32', english: 'advance', chinese: '进步', pos: 'v', example: 'We advance in our science.', exampleChinese: '我们在科学上取得了进步。' }
];

const u7: Word[] = [
  { id: 'u7-1', english: 'breakfast', chinese: '早餐', pos: 'n', example: 'I have eggs for breakfast.', exampleChinese: '我早餐吃鸡蛋。' },
  { id: 'u7-2', english: 'lunch', chinese: '午餐', pos: 'n', example: 'We have lunch at school.', exampleChinese: '我们在学校吃午餐。' },
  { id: 'u7-3', english: 'dinner', chinese: '晚餐', pos: 'n', example: 'What is for dinner today?', exampleChinese: '今天晚饭吃什么？' },
  { id: 'u7-4', english: 'restaurant', chinese: '饭馆', pos: 'n', example: 'Let us go to a restaurant.', exampleChinese: '让我们去饭馆吧。' },
  { id: 'u7-5', english: 'menu', chinese: '菜单', pos: 'n', example: 'Can I see the menu?', exampleChinese: '我能看下菜单吗？' },
  { id: 'u7-6', english: 'order', chinese: '点餐', pos: 'v', example: 'I want to order pizza.', exampleChinese: '我想点比萨。' },
  { id: 'u7-7', english: 'waiter', chinese: '服务生', pos: 'n', example: 'The waiter is very kind.', exampleChinese: '那个服务生很亲切。' },
  { id: 'u7-8', english: 'serve', chinese: '服务', pos: 'v', example: 'They serve good food here.', exampleChinese: '他们这里提供美味的食物。' },
  { id: 'u7-9', english: 'kitchen', chinese: '厨房', pos: 'n', example: 'Dad is cooking in kitchen.', exampleChinese: '爸爸在厨房做饭。' },
  { id: 'u7-10', english: 'chef', chinese: '厨师', pos: 'n', example: 'He is a great chef.', exampleChinese: '他是个伟大的厨师。' },
  { id: 'u7-11', english: 'recipe', chinese: '食谱', pos: 'n', example: 'I follow the cake recipe.', exampleChinese: '我遵循蛋糕食谱。' },
  { id: 'u7-12', english: 'ingredient', chinese: '配料', pos: 'n', example: 'Mix all the ingredients together.', exampleChinese: '把所有配料混合在一起。' },
  { id: 'u7-13', english: 'flour', chinese: '面粉', pos: 'n', example: 'Bread is made from flour.', exampleChinese: '面包是用面粉做的。' },
  { id: 'u7-14', english: 'salt', chinese: '盐', pos: 'n', example: 'Do not add too much salt.', exampleChinese: '不要放太多的盐。' },
  { id: 'u7-15', english: 'spice', chinese: '香料', pos: 'n', example: 'I like some hot spice.', exampleChinese: '我喜欢一些辣的香料。' },
  { id: 'u7-16', english: 'oil', chinese: '油', pos: 'n', example: 'We use oil for cooking.', exampleChinese: '我们用油做饭。' },
  { id: 'u7-17', english: 'boil', chinese: '煮沸', pos: 'v', example: 'Boil the water for tea.', exampleChinese: '烧开水泡茶。' },
  { id: 'u7-18', english: 'fry', chinese: '油炸', pos: 'v', example: 'I like to fry fish.', exampleChinese: '我喜欢煎鱼。' },
  { id: 'u7-19', english: 'bake', chinese: '烘焙', pos: 'v', example: 'Mom will bake some cookies.', exampleChinese: '妈妈会烤一些曲奇。' },
  { id: 'u7-20', english: 'roast', chinese: '烤制', pos: 'v', example: 'We roast chicken for dinner.', exampleChinese: '我们晚饭烤鸡吃。' },
  { id: 'u7-21', english: 'sweet', chinese: '甜的', pos: 'adj', example: 'This apple is very sweet.', exampleChinese: '这个苹果很甜。' },
  { id: 'u7-22', english: 'sour', chinese: '酸的', pos: 'adj', example: 'The lemon is very sour.', exampleChinese: '柠檬非常酸。' },
  { id: 'u7-23', english: 'bitter', chinese: '苦的', pos: 'adj', example: 'Coffee has a bitter taste.', exampleChinese: '咖啡有一种苦味。' },
  { id: 'u7-24', english: 'spicy', chinese: '辣的', pos: 'adj', example: 'I love eating spicy food.', exampleChinese: '我喜欢吃辣的食物。' },
  { id: 'u7-25', english: 'dessert', chinese: '甜点', pos: 'n', example: 'What dessert do you like?', exampleChinese: '你喜欢什么甜点？' },
  { id: 'u7-26', english: 'cake', chinese: '蛋糕', pos: 'n', example: 'This is my birthday cake.', exampleChinese: '这是我的生日蛋糕。' },
  { id: 'u7-27', english: 'fruit', chinese: '水果', pos: 'n', example: 'Fruit is good for you.', exampleChinese: '水果对你有好处。' },
  { id: 'u7-28', english: 'cheese', chinese: '奶酪', pos: 'n', example: 'I put cheese on bread.', exampleChinese: '我在面包上放奶酪。' },
  { id: 'u7-29', english: 'juice', chinese: '果汁', pos: 'n', example: 'Give me some orange juice.', exampleChinese: '给我一些橙汁。' },
  { id: 'u7-30', english: 'drink', chinese: '喝', pos: 'v', example: 'You must drink more water.', exampleChinese: '你必须多喝水。' },
  { id: 'u7-31', english: 'full', chinese: '饱的', pos: 'adj', example: 'I cannot eat more I am full.', exampleChinese: '我不能再吃了，我饱了。' },
  { id: 'u7-32', english: 'thirsty', chinese: '渴的', pos: 'adj', example: 'Can I have some water I am thirsty.', exampleChinese: '我能喝点水吗，我渴了。' }
];

const u8: Word[] = [
  { id: 'u8-1', english: 'knowledge', chinese: '知识', pos: 'n', example: 'Reading gives us much knowledge.', exampleChinese: '读书给我们很多知识。' },
  { id: 'u8-2', english: 'wisdom', chinese: '智慧', pos: 'n', example: 'The old man has wisdom.', exampleChinese: '那位老人很有智慧。' },
  { id: 'u8-3', english: 'focus', chinese: '专注', pos: 'v', example: 'Focus on your study now.', exampleChinese: '现在专注于你的学习。' },
  { id: 'u8-4', english: 'attention', chinese: '注意力', pos: 'n', example: 'Please pay attention to me.', exampleChinese: '请注意听我说话。' },
  { id: 'u8-5', english: 'memory', chinese: '记忆', pos: 'n', example: 'He has a good memory.', exampleChinese: '他有很好的记忆力。' },
  { id: 'u8-6', english: 'brain', chinese: '大脑', pos: 'n', example: 'Use your brain to think.', exampleChinese: '动脑筋思考。' },
  { id: 'u8-7', english: 'think', chinese: '思考', pos: 'v', example: 'Think about the question again.', exampleChinese: '再考虑一下这个问题。' },
  { id: 'u8-8', english: 'logic', chinese: '逻辑', pos: 'n', example: 'The story has no logic.', exampleChinese: '这个故事没有逻辑。' },
  { id: 'u8-9', english: 'problem', chinese: '问题', pos: 'n', example: 'I solved the math problem.', exampleChinese: '我解决了这道数学题。' },
  { id: 'u8-10', english: 'solution', chinese: '解决方案', pos: 'n', example: 'We found a good solution.', exampleChinese: '我们找到了一个好办法。' },
  { id: 'u8-11', english: 'solve', chinese: '解决', pos: 'v', example: 'Can you solve this riddle?', exampleChinese: '你能解开这个谜语吗？' },
  { id: 'u8-12', english: 'difficulty', chinese: '困难', pos: 'n', example: 'They faced many life difficulties.', exampleChinese: '他们面临许多生活困难。' },
  { id: 'u8-13', english: 'challenge', chinese: '挑战', pos: 'n', example: 'It is a big challenge.', exampleChinese: '这是一个大挑战。' },
  { id: 'u8-14', english: 'courage', chinese: '勇气', pos: 'n', example: 'You have courage to try.', exampleChinese: '你有勇气去尝试。' },
  { id: 'u8-15', english: 'goal', chinese: '目标', pos: 'n', example: 'My goal is to learn.', exampleChinese: '我的目标是学习。' },
  { id: 'u8-16', english: 'plan', chinese: '计划', pos: 'n', example: 'I have a holiday plan.', exampleChinese: '我有一个假期计划。' },
  { id: 'u8-17', english: 'success', chinese: '成功', pos: 'n', example: 'Hard work brings great success.', exampleChinese: '努力工作带来成功。' },
  { id: 'u8-18', english: 'failure', chinese: '失败', pos: 'n', example: 'Do not fear the failure.', exampleChinese: '不要害怕失败。' },
  { id: 'u8-19', english: 'trial', chinese: '试验', pos: 'n', example: 'This is a new trial.', exampleChinese: '这是一次新的尝试。' },
  { id: 'u8-20', english: 'attempt', chinese: '尝试', pos: 'v', example: 'I will attempt to swim.', exampleChinese: '我会尝试游泳。' },
  { id: 'u8-21', english: 'persistent', chinese: '坚持的', pos: 'adj', example: 'You must be more persistent.', exampleChinese: '你必须更坚持。' },
  { id: 'u8-22', english: 'patience', chinese: '耐心', pos: 'n', example: 'Wait with some more patience.', exampleChinese: '再耐心等一会儿。' },
  { id: 'u8-23', english: 'dream', chinese: '梦想', pos: 'n', example: 'Follow your beautiful dream now.', exampleChinese: '现在追随你美好的梦想吧。' },
  { id: 'u8-24', english: 'imagine', chinese: '想象', pos: 'v', example: 'Can you imagine the future?', exampleChinese: '你能想象未来吗？' },
  { id: 'u8-25', english: 'library', chinese: '图书馆', pos: 'n', example: 'The library is very quiet.', exampleChinese: '图书馆非常安静。' },
  { id: 'u8-26', english: 'book', chinese: '书', pos: 'n', example: 'Read this interesting book now.', exampleChinese: '现在读读这本有趣的书。' },
  { id: 'u8-27', english: 'poem', chinese: '诗歌', pos: 'n', example: 'She wrote a short poem.', exampleChinese: '她写了一首短诗。' },
  { id: 'u8-28', english: 'literature', chinese: '文学', pos: 'n', example: 'I love English literature class.', exampleChinese: '我喜欢英语文学课。' },
  { id: 'u8-29', english: 'art', chinese: '艺术', pos: 'n', example: 'He is good at art.', exampleChinese: '他擅长艺术。' },
  { id: 'u8-30', english: 'skill', chinese: '技能', pos: 'n', example: 'You have good reading skills.', exampleChinese: '你有很好的阅读技巧。' },
  { id: 'u8-31', english: 'practice', chinese: '练习', pos: 'v', example: 'Practice makes perfect every day.', exampleChinese: '熟能生巧。' },
  { id: 'u8-32', english: 'expert', chinese: '专家', pos: 'n', example: 'He is a computer expert.', exampleChinese: '他是位电脑专家。' }
];

export const RAW_WORDS: Record<number, Word[]> = {
  1: u1,
  2: u2,
  3: u3,
  4: u4,
  5: u5,
  6: u6,
  7: u7,
  8: u8
};

export const WORLD_COLORS: Record<number, string> = {
  1: 'bg-emerald-500', 2: 'bg-amber-500', 3: 'bg-blue-500', 
  4: 'bg-purple-500', 5: 'bg-indigo-500', 6: 'bg-cyan-500',
  7: 'bg-rose-500', 8: 'bg-orange-500'
};
